language: objective-c
os: osx

install:
  - brew install python3
  - which python3
  - pip3 install --upgrade pip3
  - pip3 install pipenv
  - pipenv install --dev

script:
  - pipenv run python build_u3d.py
  - pipenv run python build_vtku3dexporter.py
  - pipenv run python setup.py bdist_wheel
  - pipenv run pip install dist/VTKU3DExporter*.whl
  - pipenv run python src/u3d/Samples/SampleCode/test.py
