language: objective-c
os: osx
osx_image: xcode9.2

install:
  - brew install python3
  - which python3
  - pip3 install --upgrade pip setuptools wheel || true
  - pip3 install pipenv || true
  - pipenv --version
  - pipenv install --dev
  - pipenv graph
  - cat Pipfile.lock
  - python3 -c "import json; data = json.load(open('Pipfile.lock')); assert data['default']['vtk']['index'] == 'berend'"

script:
  - pipenv run python build_u3d.py
  - pipenv run python build_vtku3dexporter.py
  - pipenv run python setup.py bdist_wheel
  - pipenv run pip install dist/VTKU3DExporter*.whl
  - pipenv run python src/u3d/Samples/SampleCode/test.py
