language: objective-c
os: osx
osx_image: xcode9.2

install:
  - brew install python3
  - brew install pipenv
  - pipenv --version
  - pipenv install --dev --skip-lock
  - pipenv graph
  - ls $(pipenv --venv)/include
  - if [[ -d $(pipenv --venv)/include/vtk-8.1 ]]; then return 1; fi

script:
  - pipenv run python build_u3d.py
  - pipenv run python build_vtku3dexporter.py
  - pipenv run python setup.py bdist_wheel
  - pipenv run pip install dist/VTKU3DExporter*.whl
  - pipenv run python src/u3d/Samples/SampleCode/test.py
